version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: it_planeta_postgres
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=2023_it_planeta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - JWT_KEY=744db172ac69d4a88983b88f97f69ee6
  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: it_planeta_api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234