// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"
)

type Account struct {
	Username string
	Password string
	IsAdmin  bool
	Balance  float64
}

type Rent struct {
	ID          int32
	UserId      string
	TransportId string
	TimeStart   time.Time
	TimeEnd     sql.NullTime
	PriceOfUnit float64
	PriceType   string
	FinalPrice  sql.NullFloat64
}

type Transport struct {
	ID            string
	OwnerId       string
	TransportType string
	Model         string
	Color         string
	Description   sql.NullString
	Latitude      float64
	Longitude     float64
	MinutePrice   sql.NullFloat64
	DayPrice      sql.NullFloat64
}

type TransportType struct {
	Name string
}
