// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"
)

type Account struct {
	Username string
	Password string
	Balance  float64
}

type AccountRole struct {
	Account string
	Role    string
}

type Rent struct {
	ID        int32
	Account   string
	Transport string
	TimeStart time.Time
	TimeEnd   sql.NullTime
	PriceUnit float64
	PriceType string
}

type Role struct {
	Name string
}

type Transport struct {
	ID          string
	Owner       string
	Transport   string
	Model       string
	Color       string
	Description sql.NullString
	Latitude    float64
	Longitude   float64
	MinutePrice sql.NullFloat64
	DayPrice    sql.NullFloat64
}

type TransportType struct {
	Name string
}
