// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const appendRoleAccount = `-- name: AppendRoleAccount :one
INSERT INTO "AccountRole" (account, "role")
VALUES ($1, $2)
RETURNING account, role
`

type AppendRoleAccountParams struct {
	Account int32
	Role    string
}

func (q *Queries) AppendRoleAccount(ctx context.Context, arg AppendRoleAccountParams) (AccountRole, error) {
	row := q.db.QueryRowContext(ctx, appendRoleAccount, arg.Account, arg.Role)
	var i AccountRole
	err := row.Scan(&i.Account, &i.Role)
	return i, err
}

const appendTokenToBlackList = `-- name: AppendTokenToBlackList :exec
INSERT INTO "TokenBlackList" (token)
VALUES ($1)
`

func (q *Queries) AppendTokenToBlackList(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, appendTokenToBlackList, token)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO "Account" (username, "password", balance, deleted)
VALUES ($1, $2, $3, false)
RETURNING id, username, password, balance, deleted
`

type CreateAccountParams struct {
	Username string
	Password string
	Balance  float64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Username, arg.Password, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Balance,
		&i.Deleted,
	)
	return i, err
}

const createRent = `-- name: CreateRent :one
INSERT INTO "Rent" (account, transport, time_start, time_end, price_unit, price_type, deleted)
VALUES ($1, $2, $3, $4, $5, $6, false)
RETURNING id, account, transport, time_start, time_end, price_unit, price_type, deleted
`

type CreateRentParams struct {
	Account   int32
	Transport int32
	TimeStart time.Time
	TimeEnd   sql.NullTime
	PriceUnit float64
	PriceType string
}

func (q *Queries) CreateRent(ctx context.Context, arg CreateRentParams) (Rent, error) {
	row := q.db.QueryRowContext(ctx, createRent,
		arg.Account,
		arg.Transport,
		arg.TimeStart,
		arg.TimeEnd,
		arg.PriceUnit,
		arg.PriceType,
	)
	var i Rent
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Transport,
		&i.TimeStart,
		&i.TimeEnd,
		&i.PriceUnit,
		&i.PriceType,
		&i.Deleted,
	)
	return i, err
}

const createTransport = `-- name: CreateTransport :one
INSERT INTO "Transport"
("owner", "type", can_rented, model, color, "description", identifier, latitude, longitude, minute_price, day_price, deleted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, false)
RETURNING id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
`

type CreateTransportParams struct {
	Owner       int32
	Type        string
	CanRented   bool
	Model       string
	Color       string
	Description sql.NullString
	Identifier  string
	Latitude    float64
	Longitude   float64
	MinutePrice sql.NullFloat64
	DayPrice    sql.NullFloat64
}

func (q *Queries) CreateTransport(ctx context.Context, arg CreateTransportParams) (Transport, error) {
	row := q.db.QueryRowContext(ctx, createTransport,
		arg.Owner,
		arg.Type,
		arg.CanRented,
		arg.Model,
		arg.Color,
		arg.Description,
		arg.Identifier,
		arg.Latitude,
		arg.Longitude,
		arg.MinutePrice,
		arg.DayPrice,
	)
	var i Transport
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Type,
		&i.CanRented,
		&i.Model,
		&i.Color,
		&i.Identifier,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.MinutePrice,
		&i.DayPrice,
		&i.Deleted,
	)
	return i, err
}

const deleteAccountRoles = `-- name: DeleteAccountRoles :exec
DELETE
FROM "AccountRole"
WHERE account=$1
`

func (q *Queries) DeleteAccountRoles(ctx context.Context, account int32) error {
	_, err := q.db.ExecContext(ctx, deleteAccountRoles, account)
	return err
}

const endRent = `-- name: EndRent :exec
UPDATE "Rent"
SET time_end=$1
WHERE id=$2
`

type EndRentParams struct {
	TimeEnd sql.NullTime
	ID      int32
}

func (q *Queries) EndRent(ctx context.Context, arg EndRentParams) error {
	_, err := q.db.ExecContext(ctx, endRent, arg.TimeEnd, arg.ID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, password, balance, deleted
FROM "Account"
WHERE id=$1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Balance,
		&i.Deleted,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, password, balance, deleted
FROM "Account"
WHERE username=$1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Balance,
		&i.Deleted,
	)
	return i, err
}

const getAccountRoles = `-- name: GetAccountRoles :many
SELECT "role"
FROM "AccountRole"
WHERE account=$1
`

func (q *Queries) GetAccountRoles(ctx context.Context, account int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAccountRoles, account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccounts = `-- name: GetAccounts :many
SELECT
    a.id, a.username, a.password, a.balance, a.deleted,
    json_agg(r.name) AS roles
FROM
    "Account" AS a
JOIN
    "AccountRole" AS ar ON a.id = ar.account
JOIN
    "Role" AS r ON ar.role = r.name
GROUP BY
    a.id
OFFSET $1 LIMIT $2
`

type GetAccountsParams struct {
	Offset int32
	Limit  int32
}

type GetAccountsRow struct {
	ID       int32
	Username string
	Password string
	Balance  float64
	Deleted  bool
	Roles    json.RawMessage
}

func (q *Queries) GetAccounts(ctx context.Context, arg GetAccountsParams) ([]GetAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccounts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsRow
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Balance,
			&i.Deleted,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCacheRoles = `-- name: GetCacheRoles :many
SELECT account, role
FROM "AccountRole"
`

func (q *Queries) GetCacheRoles(ctx context.Context) ([]AccountRole, error) {
	rows, err := q.db.QueryContext(ctx, getCacheRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountRole
	for rows.Next() {
		var i AccountRole
		if err := rows.Scan(&i.Account, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistAccounts = `-- name: GetExistAccounts :many
SELECT
    a.id, a.username, a.password, a.balance, a.deleted,
    json_agg(r.name) AS roles
FROM
    "Account" AS a
JOIN
    "AccountRole" AS ar ON a.id = ar.account
JOIN
    "Role" AS r ON ar.role = r.name
WHERE
    a.deleted = false
GROUP BY
    a.id
OFFSET $1 LIMIT $2
`

type GetExistAccountsParams struct {
	Offset int32
	Limit  int32
}

type GetExistAccountsRow struct {
	ID       int32
	Username string
	Password string
	Balance  float64
	Deleted  bool
	Roles    json.RawMessage
}

func (q *Queries) GetExistAccounts(ctx context.Context, arg GetExistAccountsParams) ([]GetExistAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExistAccounts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExistAccountsRow
	for rows.Next() {
		var i GetExistAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Balance,
			&i.Deleted,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRent = `-- name: GetRent :one
SELECT id, account, transport, time_start, time_end, price_unit, price_type, deleted
FROM "Rent"
WHERE "Rent".id=$1
`

func (q *Queries) GetRent(ctx context.Context, id int32) (Rent, error) {
	row := q.db.QueryRowContext(ctx, getRent, id)
	var i Rent
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Transport,
		&i.TimeStart,
		&i.TimeEnd,
		&i.PriceUnit,
		&i.PriceType,
		&i.Deleted,
	)
	return i, err
}

const getRentsFromID = `-- name: GetRentsFromID :many
SELECT id, account, transport, time_start, time_end, price_unit, price_type, deleted
FROM "Rent"
WHERE account=$1
OFFSET $2 LIMIT $3
`

type GetRentsFromIDParams struct {
	Account int32
	Offset  int32
	Limit   int32
}

func (q *Queries) GetRentsFromID(ctx context.Context, arg GetRentsFromIDParams) ([]Rent, error) {
	rows, err := q.db.QueryContext(ctx, getRentsFromID, arg.Account, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rent
	for rows.Next() {
		var i Rent
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Transport,
			&i.TimeStart,
			&i.TimeEnd,
			&i.PriceUnit,
			&i.PriceType,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRentsFromTransportID = `-- name: GetRentsFromTransportID :many
SELECT id, account, transport, time_start, time_end, price_unit, price_type, deleted
FROM "Rent"
WHERE transport=$1
OFFSET $2 LIMIT $3
`

type GetRentsFromTransportIDParams struct {
	Transport int32
	Offset    int32
	Limit     int32
}

func (q *Queries) GetRentsFromTransportID(ctx context.Context, arg GetRentsFromTransportIDParams) ([]Rent, error) {
	rows, err := q.db.QueryContext(ctx, getRentsFromTransportID, arg.Transport, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rent
	for rows.Next() {
		var i Rent
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Transport,
			&i.TimeStart,
			&i.TimeEnd,
			&i.PriceUnit,
			&i.PriceType,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransport = `-- name: GetTransport :one
SELECT id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
FROM "Transport"
WHERE id=$1
`

func (q *Queries) GetTransport(ctx context.Context, id int32) (Transport, error) {
	row := q.db.QueryRowContext(ctx, getTransport, id)
	var i Transport
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Type,
		&i.CanRented,
		&i.Model,
		&i.Color,
		&i.Identifier,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.MinutePrice,
		&i.DayPrice,
		&i.Deleted,
	)
	return i, err
}

const getTransports = `-- name: GetTransports :many
SELECT id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
FROM "Transport"
ORDER BY id
OFFSET $1 LIMIT $2
`

type GetTransportsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetTransports(ctx context.Context, arg GetTransportsParams) ([]Transport, error) {
	rows, err := q.db.QueryContext(ctx, getTransports, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transport
	for rows.Next() {
		var i Transport
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Type,
			&i.CanRented,
			&i.Model,
			&i.Color,
			&i.Identifier,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.MinutePrice,
			&i.DayPrice,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportsFromRadiusAll = `-- name: GetTransportsFromRadiusAll :many
SELECT id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
FROM "Transport"
WHERE
    "can_rented"=true
    and point(longitude, latitude) <@> point($1, $2) <= $3
`

type GetTransportsFromRadiusAllParams struct {
	Point     float64
	Point_2   float64
	Longitude float64
}

func (q *Queries) GetTransportsFromRadiusAll(ctx context.Context, arg GetTransportsFromRadiusAllParams) ([]Transport, error) {
	rows, err := q.db.QueryContext(ctx, getTransportsFromRadiusAll, arg.Point, arg.Point_2, arg.Longitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transport
	for rows.Next() {
		var i Transport
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Type,
			&i.CanRented,
			&i.Model,
			&i.Color,
			&i.Identifier,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.MinutePrice,
			&i.DayPrice,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportsFromRadiusOnlyType = `-- name: GetTransportsFromRadiusOnlyType :many
SELECT id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
FROM "Transport"
WHERE
    "can_rented"=true
    and "type"=$1
    and point(longitude, latitude) <@> point($2, $3) <= $4
`

type GetTransportsFromRadiusOnlyTypeParams struct {
	Type      string
	Point     float64
	Point_2   float64
	Longitude float64
}

func (q *Queries) GetTransportsFromRadiusOnlyType(ctx context.Context, arg GetTransportsFromRadiusOnlyTypeParams) ([]Transport, error) {
	rows, err := q.db.QueryContext(ctx, getTransportsFromRadiusOnlyType,
		arg.Type,
		arg.Point,
		arg.Point_2,
		arg.Longitude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transport
	for rows.Next() {
		var i Transport
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Type,
			&i.CanRented,
			&i.Model,
			&i.Color,
			&i.Identifier,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.MinutePrice,
			&i.DayPrice,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportsOnlyType = `-- name: GetTransportsOnlyType :many
SELECT id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
FROM "Transport"
WHERE "type"=$1
ORDER BY id
OFFSET $2 LIMIT $3
`

type GetTransportsOnlyTypeParams struct {
	Type   string
	Offset int32
	Limit  int32
}

func (q *Queries) GetTransportsOnlyType(ctx context.Context, arg GetTransportsOnlyTypeParams) ([]Transport, error) {
	rows, err := q.db.QueryContext(ctx, getTransportsOnlyType, arg.Type, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transport
	for rows.Next() {
		var i Transport
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Type,
			&i.CanRented,
			&i.Model,
			&i.Color,
			&i.Identifier,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.MinutePrice,
			&i.DayPrice,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAccountExistByID = `-- name: IsAccountExistByID :one
SELECT EXISTS (
  SELECT 1
  FROM "Account"
  WHERE id=$1
)
`

func (q *Queries) IsAccountExistByID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountExistByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountExistByUsername = `-- name: IsAccountExistByUsername :one
SELECT EXISTS (
  SELECT 1
  FROM "Account"
  WHERE username=$1
)
`

func (q *Queries) IsAccountExistByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountExistByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountRemovedByID = `-- name: IsAccountRemovedByID :one
SELECT EXISTS (
  SELECT 1
  FROM "Account"
  WHERE id=$1 and deleted=true
)
`

func (q *Queries) IsAccountRemovedByID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountRemovedByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountRemovedByUsername = `-- name: IsAccountRemovedByUsername :one
SELECT EXISTS (
  SELECT 1
  FROM "Account"
  WHERE username=$1 and deleted=true
)
`

func (q *Queries) IsAccountRemovedByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAccountRemovedByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isContainBlackListToken = `-- name: IsContainBlackListToken :one
SELECT EXISTS (
  SELECT 1
  FROM "TokenBlackList"
  WHERE token=$1
)
`

func (q *Queries) IsContainBlackListToken(ctx context.Context, token string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isContainBlackListToken, token)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isExistCurrentRent = `-- name: IsExistCurrentRent :one
SELECT EXISTS (
    SELECT 1
    FROM "Rent"
    WHERE transport=$1 and time_end=null
)
`

func (q *Queries) IsExistCurrentRent(ctx context.Context, transport int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isExistCurrentRent, transport)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isExistTransportByID = `-- name: IsExistTransportByID :one
SELECT EXISTS (
  SELECT 1
  FROM "Transport"
  WHERE id=$1
)
`

func (q *Queries) IsExistTransportByID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isExistTransportByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isExistTransportByIdentifier = `-- name: IsExistTransportByIdentifier :one
SELECT EXISTS (
  SELECT 1
  FROM "Transport"
  WHERE identifier=$1
)
`

func (q *Queries) IsExistTransportByIdentifier(ctx context.Context, identifier string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isExistTransportByIdentifier, identifier)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRentExist = `-- name: IsRentExist :one
SELECT EXISTS (
  SELECT 1
  FROM "Rent"
  WHERE id=$1
)
`

func (q *Queries) IsRentExist(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRentExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRentRemoved = `-- name: IsRentRemoved :one
SELECT EXISTS (
  SELECT 1
  FROM "Rent"
  WHERE id=$1 and deleted=true
)
`

func (q *Queries) IsRentRemoved(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRentRemoved, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRenter = `-- name: IsRenter :one
SELECT EXISTS (
  SELECT 1
  FROM "Rent"
  WHERE id=$1 and account=$2
)
`

type IsRenterParams struct {
	ID      int32
	Account int32
}

func (q *Queries) IsRenter(ctx context.Context, arg IsRenterParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRenter, arg.ID, arg.Account)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isTransportOwner = `-- name: IsTransportOwner :one
SELECT EXISTS (
  SELECT 1
  FROM "Transport"
  WHERE id=$1 and "owner"=$2
)
`

type IsTransportOwnerParams struct {
	ID    int32
	Owner int32
}

func (q *Queries) IsTransportOwner(ctx context.Context, arg IsTransportOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTransportOwner, arg.ID, arg.Owner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isTransportRemoved = `-- name: IsTransportRemoved :one
SELECT EXISTS (
  SELECT 1
  FROM "Transport"
  WHERE id=$1 and deleted=true
)
`

func (q *Queries) IsTransportRemoved(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTransportRemoved, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeAccount = `-- name: RemoveAccount :exec
UPDATE "Account"
SET deleted=true
WHERE id=$1
`

func (q *Queries) RemoveAccount(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, removeAccount, id)
	return err
}

const removeRent = `-- name: RemoveRent :exec
UPDATE "Rent"
SET deleted=true
WHERE id=$1
`

func (q *Queries) RemoveRent(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, removeRent, id)
	return err
}

const removeTransport = `-- name: RemoveTransport :exec
UPDATE "Transport"
SET deleted=true
WHERE id=$1
`

func (q *Queries) RemoveTransport(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, removeTransport, id)
	return err
}

const replaceUsername = `-- name: ReplaceUsername :exec
UPDATE "Account"
SET username=$1
WHERE id=$2
`

type ReplaceUsernameParams struct {
	Username string
	ID       int32
}

func (q *Queries) ReplaceUsername(ctx context.Context, arg ReplaceUsernameParams) error {
	_, err := q.db.ExecContext(ctx, replaceUsername, arg.Username, arg.ID)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE "Account"
SET username=$1, "password"=$2, balance=$3
WHERE id=$4
`

type UpdateAccountParams struct {
	Username string
	Password string
	Balance  float64
	ID       int32
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Username,
		arg.Password,
		arg.Balance,
		arg.ID,
	)
	return err
}

const updateRent = `-- name: UpdateRent :one
UPDATE "Rent"
SET account=$1, transport=$2, time_start=$3, time_end=$4, price_unit=$5, price_type=$6
WHERE id=$7
RETURNING id, account, transport, time_start, time_end, price_unit, price_type, deleted
`

type UpdateRentParams struct {
	Account   int32
	Transport int32
	TimeStart time.Time
	TimeEnd   sql.NullTime
	PriceUnit float64
	PriceType string
	ID        int32
}

func (q *Queries) UpdateRent(ctx context.Context, arg UpdateRentParams) (Rent, error) {
	row := q.db.QueryRowContext(ctx, updateRent,
		arg.Account,
		arg.Transport,
		arg.TimeStart,
		arg.TimeEnd,
		arg.PriceUnit,
		arg.PriceType,
		arg.ID,
	)
	var i Rent
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Transport,
		&i.TimeStart,
		&i.TimeEnd,
		&i.PriceUnit,
		&i.PriceType,
		&i.Deleted,
	)
	return i, err
}

const updateTransport = `-- name: UpdateTransport :one
UPDATE "Transport"
SET can_rented=$1, model=$2, color=$3, "description"=$4, latitude=$5, longitude=$6, minute_price=$7, day_price=$8, identifier=$9
WHERE id=$10
RETURNING id, owner, type, can_rented, model, color, identifier, description, latitude, longitude, minute_price, day_price, deleted
`

type UpdateTransportParams struct {
	CanRented   bool
	Model       string
	Color       string
	Description sql.NullString
	Latitude    float64
	Longitude   float64
	MinutePrice sql.NullFloat64
	DayPrice    sql.NullFloat64
	Identifier  string
	ID          int32
}

func (q *Queries) UpdateTransport(ctx context.Context, arg UpdateTransportParams) (Transport, error) {
	row := q.db.QueryRowContext(ctx, updateTransport,
		arg.CanRented,
		arg.Model,
		arg.Color,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.MinutePrice,
		arg.DayPrice,
		arg.Identifier,
		arg.ID,
	)
	var i Transport
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Type,
		&i.CanRented,
		&i.Model,
		&i.Color,
		&i.Identifier,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.MinutePrice,
		&i.DayPrice,
		&i.Deleted,
	)
	return i, err
}
