FROM postgres:14-alpine

ENV POSTGRES_DB=it_planeta
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234

COPY ././queries/schema.sql ./docker-entrypoint-initdb.d/_schema.sql
COPY ././migrations/init_values.sql ./docker-entrypoint-initdb.d/init_values.sql

EXPOSE 5432
